In [3]:
import numpy as np

In [24]:
puzzle = [[0, 0, 0, 0, 9, 1, 4, 0, 0],
          [0, 0, 0, 0, 0, 0, 0, 6, 0], 
          [5, 0, 0, 0, 0, 4, 9, 0, 0], 
          [7, 0, 4, 0, 0, 8, 0, 5, 0], 
          [0, 0, 0, 0, 2, 0, 0, 0, 1], 
          [0, 2, 0, 0, 0, 0, 0, 0, 4], 
          [0, 0, 6, 3, 0, 0, 5, 0, 7], 
          [0, 0, 0, 0, 7, 6, 0, 0, 0], 
          [0, 0, 7, 0, 1, 0, 0, 0, 0]]

In [25]:
puzzle = np.array(puzzle)
print(puzzle)

[[0 0 0 0 9 1 4 0 0]
 [0 0 0 0 0 0 0 6 0]
 [5 0 0 0 0 4 9 0 0]
 [7 0 4 0 0 8 0 5 0]
 [0 0 0 0 2 0 0 0 1]
 [0 2 0 0 0 0 0 0 4]
 [0 0 6 3 0 0 5 0 7]
 [0 0 0 0 7 6 0 0 0]
 [0 0 7 0 1 0 0 0 0]]


In [26]:
def possible(x, y, n):
    global puzzle
    # test if n possible in x
    for i in range(9):
        if puzzle[x,i] == n:
            return False
    for i in range(9):
        if puzzle[i,y] == n:
            return False
    sx = int(np.floor(x/3)*3)
    sy = int(np.floor(y/3)*3)
    for i in range(sx, sx+3):
        for j in range(sy, sy+3):
            if puzzle[i, j] == n:
                return False
    return True
    
    # test if n possible in y
    # test if n possible in square

In [27]:
def solve():
    global puzzle
    for i in range(9):
        for j in range(9):
            if puzzle[i, j] == 0:
                for k in range(1,10):
                    if possible(i, j, k):
                        puzzle[i, j] = k
                        solve()
                        # back track incase bad selection
                        puzzle[i][j] = 0
                return
    print(puzzle)
    input('Show another solution?')

In [ ]:
solve()

[[2 3 8 6 9 1 4 7 5]
 [4 7 9 2 3 5 1 6 8]
 [5 6 1 7 8 4 9 2 3]
 [7 1 4 9 6 8 3 5 2]
 [6 8 5 4 2 3 7 9 1]
 [9 2 3 1 5 7 6 8 4]
 [8 9 6 3 4 2 5 1 7]
 [1 4 2 5 7 6 8 3 9]
 [3 5 7 8 1 9 2 4 6]]


Show another solution? 


[[2 3 8 6 9 1 4 7 5]
 [4 7 9 2 3 5 1 6 8]
 [5 6 1 7 8 4 9 2 3]
 [7 1 4 9 6 8 3 5 2]
 [6 9 5 4 2 3 7 8 1]
 [8 2 3 1 5 7 6 9 4]
 [9 8 6 3 4 2 5 1 7]
 [1 4 2 5 7 6 8 3 9]
 [3 5 7 8 1 9 2 4 6]]


Show another solution? 


[[2 3 8 6 9 1 4 7 5]
 [4 7 9 2 3 5 1 6 8]
 [5 6 1 7 8 4 9 3 2]
 [7 1 4 9 6 8 2 5 3]
 [6 8 5 4 2 3 7 9 1]
 [9 2 3 1 5 7 6 8 4]
 [8 9 6 3 4 2 5 1 7]
 [1 5 2 8 7 6 3 4 9]
 [3 4 7 5 1 9 8 2 6]]
